printing-page - model-exemples
dj-egregor/project-group-5 pull request #14
Opened 2022-09-09 14:26 UTC by KateSkrypchenko

Короче.  Обрати внимания на макете - расстояния между картинкой и подписью везде разные. Вечером поговорим, может будет у когото другие идет - тогда переделаю. А так я задавала марджины

2022-09-09 21:32 UTC, dj-egregor commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples {
синтаксическая ошибка model-examples должно быть))))

2022-09-09 21:32 UTC, dj-egregor commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__title {
examples

2022-09-09 21:32 UTC, dj-egregor commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__list {
examples

2022-09-09 21:32 UTC, dj-egregor commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__text {
короче везде examples

2022-09-09 21:33 UTC, KateSkrypchenko commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__title {
А я то думаю, чё оно мне ругалось)

2022-09-09 21:33 UTC, KateSkrypchenko commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__text {
Я поняла, исправлю

2022-09-09 21:34 UTC, dj-egregor commented on src/partials/printing-page/model-examples.html
> +<section class="model-exemples">
model-exemples ошибка, надо -> model-examples  **exAmples** Плз исправь это везде)))))

2022-09-09 21:37 UTC, dj-egregor commented on src/sass/pages/printing-page/_model-examples.scss
> +.model-exemples__item {
```suggestion
.model-examples__item {
```

2022-09-09 21:54 UTC, dj-egregor requested changes
Надо исправить exemples на examples )) И ошибка по отображению текста под картинками.. при ширине 1400+ текст пляшет

2022-09-10 12:34 UTC, dj-egregor approved these changes

2022-09-10 12:35 UTC, merged