3d modelling
dj-egregor/project-group-5 pull request #9
Opened 2022-09-08 19:50 UTC by MarynaSkoryk

create section for mobile
images for 1x and 2x
we need 3x?

2022-09-08 21:20 UTC, dj-egregor requested changes
Привет, я оставил коменты в коде, там вопросы по названию шрифтов и ненужная вложенность секций

2022-09-08 21:20 UTC, dj-egregor commented on src/modeling.html
> +    <section class="modeling-hero">
В секции `<section class="modeling-hero">` размещен весь контент страницы))

Эти секции не должны быть вложены друг в друга. Каждая секция должна быть в одном файле :)

2022-09-08 21:20 UTC, dj-egregor commented on src/sass/pages/modeling-page/_hero.scss
> +.modeling-hero {
Рекомендую юзать & для сокращения кода пример:
```
.modeling-hero {  
  padding-top: 40px;
  padding-bottom: 60px;

&__main-title {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: 700;
  font-size: 24px;
  line-height: 30px;
  color: $secondary-color-text;
  text-transform: uppercase;
  margin-bottom: 16px;
  }
}
```

2022-09-08 21:20 UTC, dj-egregor commented on src/sass/pages/modeling-page/_hero.scss
> +  font-family: 'Cera Pro';
Шрифт называется Cera Pro Regular, необходимо исправить названия шрифтов в файлах)
**Вот все наши шрифты:**

- font-family: 'Caviar Dreams Regular';
- font-family: 'Caviar Dreams Bold';
- font-family: 'Cera Pro Light';
- font-family: 'Cera Pro Regular';
- font-family: 'Cera Pro Medium';
- font-family: 'Cera Pro Bold';

2022-09-08 21:20 UTC, dj-egregor commented on src/sass/pages/modeling-page/_methods-of-creations.scss
> +  font-family: 'Cera Pro';
Шрифт называется Cera Pro Regular, необходимо исправить названия шрифтов в файлах)
**Вот все наши шрифты:**

- font-family: 'Caviar Dreams Regular';
- font-family: 'Caviar Dreams Bold';
- font-family: 'Cera Pro Light';
- font-family: 'Cera Pro Regular';
- font-family: 'Cera Pro Medium';
- font-family: 'Cera Pro Bold';

2022-09-09 18:29 UTC, MarynaSkoryk commented on src/modeling.html
> +    <section class="modeling-hero">
виправила

2022-09-09 18:31 UTC, MarynaSkoryk commented on src/sass/pages/modeling-page/_hero.scss
> +.modeling-hero {
done

2022-09-09 18:32 UTC, MarynaSkoryk commented on src/sass/pages/modeling-page/_hero.scss
> +  font-family: 'Cera Pro';
ok

2022-09-09 18:33 UTC, MarynaSkoryk commented on src/sass/pages/modeling-page/_methods-of-creations.scss
> +  font-family: 'Cera Pro';
ok

2022-09-09 18:56 UTC, MarynaSkoryk commented
все виправила
видалила паршал для we-create-model - його віддасть Роман

2022-09-09 21:17 UTC, dj-egregor approved these changes
Зачем удален файл `src/sass/pages/modeling-page/_we-create-model.scss` это структура проекта ее лучше не трогать.

2022-09-09 21:21 UTC, merged